---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helium-validator
spec:
  selector:
    matchLabels:
      name: helium-validator
  serviceName: "my-helium-validator"
  replicas: 1
  template:
    metadata:
      labels:
        name: helium-validator
    spec:
      containers:
        # - name: nginx-container
        #   image: nginx
        #   volumeMounts:
        #     - name: csi-pvc
        #       mountPath: "/var/data"

        - name: validator
          image: quay.io/team-helium/validator:latest-val-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 2154
          volumeMounts:
            - name: csi-pvc
              mountPath: "/var/data"

  volumeClaimTemplates:
    - metadata:
        name: csi-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: do-block-storage