---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: validator
  serviceName: "validator"
  template:
    metadata:
      labels:
        name: validator
    spec:
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - name: validator-vol
              mountPath: "/var/data"

        - name: validator
          image: quay.io/team-helium/validator:latest-val-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 2154
          volumeMounts:
            - name: validator-vol
              mountPath: "/var/data"

  volumeClaimTemplates:
    - metadata:
        name: validator-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: do-block-storage