apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: swarm-keys
  namespace: default
spec:
  encryptedData:
    validator-0-swarm-key: AgCd2RUH7IPCOCe4weunBKmEp5v08jU/Zf6lbPdYoKEDCOnuoCob4JAG1t1ANfSGJYFV1WHZWblhjiHYosQBJLEHfdMwwxQjhU3LV1pnfDaXdkuMsibBbpBHLh5705ez+c6JFfyFDMqBwJ6oBHxvQZzjOfuqjbWAXH401mWMRAIi9lXvtF30iLevLUIgBh8LBh1WzDvscUbFD+CZl75ws9A+JWfj/u+Zai910lq00IKzC8vizKpFRx973KYe/36moOLLv6Jmkw0lUu7sIuJa5qQPQikTRx545wjdyMbtR5NvukkRYZ+ELsUytUAOh6ACwNkBX0+3zKJkUZtFf74uch89Dycw84RuX+MfJQPhpYJFIvpi01QEkEBZ3bUsD8PX+xMDg7Lp2BQNPp5S/ftPSvUCvHsHKYvrGac+g5oFQZ1KfLsSWjjWU4aprUOi5LN0mkQ7z/jHf1pexp/zXKf4oNfXcz/RrPtniMD16KHsDdD0N0r3UHlJdLzG/3G239/MQFjrpcV6VGxoquSl7xzcKKX49HJxjb6Ec1wQL/dn6Z22ij59pVYpFMFdRJM2TKQFxtnDQ/M6Oa4iIocRlP1yVm8mSmrLdUF6jivLx4xcB4bbpYyzh2/9JBLxE3S3M9jM6L5vz0HzmGzPqccEAYzGN1A9t9Y8tfi54+GTQryYGTOcqlHxHPyYh9j+EogUA7E57l4uJdcUYMd0Cq+0ZIr8MhTkqYH8AvAQoNtOb2b4lSgrhPY6j5UB2dnKgiBskSm1NMPsLxbrzITUDxW9jZXYzDjvknMyGYDY8oqfcrYylEXhYQ7DD8mNOTOmLaxkS4f84PxIDA==
    validator-1-swarm-key: AgDLRTuRYx/nMpe+uIoqVfvOqSa52jx/oDyfxUWYbR0IpEwIhUBVezQisZb2nJtSLD85piaYZbXq3F30Eyaa3IVZ2OFS+m+aYldddYisdNnI6Yi5E01B3ihX0yylSe3gtNzdN60W2jmDwlMKeXd8HSxpsE92xWsjm/c1XxyXKPrBWB6dhIiQGmYXnaw/U2l3FDGKby4JiR1MvB6QNbfVFmfVLFJF0QlD4BBBKscaGddtjspz2ZaxqBGkL7h+uWkA8Sb64PRnlH2JCj2XRBDP65aZWqf1etWkKNWwUvOXlj5WUQUFGVC6WDwy86SRjAIK1qitk11FpdY1pt+1d/Wr36xwfgURn6EW2Qz7cfylmmtzkFd8d9tzPAnCe3Y1vA1flR5KuFCOSJIKxlBHmmtYtdMImQPoFJ5qCLnbUz51mnysGGbI74nVh4SQlUSzzK0eYZ7IxWZIZR4KvGnSxCF0gzuo+gIUsgE71GwyGNXs0ra8xVng1iDIZRk3IBfrWpZj1kpQnBrm5uU0HKyMU4GdpSuy/+08q6Oj/b3t0Ux2pRx8ilvLki1EJi3O+l3zX0W2sxrAfdQsWJCp+7NG1mbyHbzdbSRt/yRX0AYrqGZK/J3TSVzNfz5dL2omHY3mvCGBcgpnOfoN9NGLHLQpji7pQyDSJ+21GqfixWYgbN5cH/9iNqh5Y/bhYNontvzhTwTpdear5MtacaJ5XGg77f+WlZ7oxNYD/zfknC15npxgjL06OunyJo7NODGsXCRn+KPloLJeYRjm3XdSXkWAfRVoKuNqa0LkVnQh17sovR8rs8Vl2MawHhJyQnbsY3GXftNNm8kWvQ==
  template:
    metadata:
      creationTimestamp: null
      name: swarm-keys
      namespace: default

