---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  replicas: 3
  selector:
    matchLabels:
      name: validator
  serviceName: "validator"
  template:
    metadata:
      labels:
        name: validator
        app: validator # being used by ServiceMonitor; could we target 'name' instead?
        dynamic-hostports: '2154' # must be a string. Split multiple ports with '.'
    spec:
      containers:
        - name: validator-exporter
          image: jamiedubs/validator-exporter:latest
          # imagePullPolicy: Never # if using local image; build in `validator-exporter` repo
          imagePullPolicy: Always
          ports:
            - containerPort: 9825 # dial 9-VAL
          volumeMounts:
            - name: validator-vol # shared w/ validator
              mountPath: /var/data
        - name: validator
          image: quay.io/team-helium/validator:latest-validator-amd64
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: "500Mi"
          command: [ "/bin/ash", "-c" ]
          args:
            - <VALIDATOR_SETUP_SCRIPT>
          env:
            - name: NAT_INTERNAL_PORT
              value: "2154"
            - name: NAT_INTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 2154
          volumeMounts:
            - name: validator-vol
              mountPath: /var/data
            - name: podinfo
              mountPath: /etc/podinfo

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

  volumeClaimTemplates:
    - metadata:
        name: validator-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: do-block-storage
