---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  podManagementPolicy: "Parallel" # Dont wait for other validators to terminate/bootup
  updateStrategy: 
    type: OnDelete # Validators wont automatically restart whenever you apply changes (use the ./scripts/restart script)
  replicas: <TOTAL_VALIDATORS>
  selector:
    matchLabels:
      name: validator
  serviceName: "validator"
  template:
    metadata:
      labels:
        name: validator
        app: validator # being used by ServiceMonitor; could we target 'name' instead?
        dynamic-hostports: '2154' # must be a string. Split multiple ports with '.'
    spec:
      shareProcessNamespace: true # otherwise you'll end up with mountains of zombie processes
      containers:
        - name: validator-exporter
          image: jamiedubs/validator-exporter:latest
          # imagePullPolicy: Never # if using local image; build in `validator-exporter` repo
          imagePullPolicy: Always
          ports:
            - containerPort: 9825 # dial 9-VAL
          volumeMounts:
            - name: validator-vol # shared w/ validator
              mountPath: /var/data
          livenessProbe:
            tcpSocket:
              port: 9825
            initialDelaySeconds: 5
        - name: validator
          image: quay.io/team-helium/validator:latest-validator-amd64
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: "1.2Gi"
          livenessProbe:
            tcpSocket:
              port: 2154
            initialDelaySeconds: 5 # using startupProbe instead; default=0
            # timeoutSeconds: 1 # time after which probe times out; default=1
            periodSeconds: 10 # check port every 5s; default=10
            failureThreshold: 20 # kill the node after 1min of unresponsiveness; default=3
          startupProbe:
            exec:
              command:
              - cat
              - /tmp/miner-started
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12 # try for 1 minute before giving up
          command: [ "/bin/ash", "-c" ]
          args:
            - <VALIDATOR_SETUP_SCRIPT>
          env:
            - name: NAT_INTERNAL_PORT
              value: "2154"
            - name: NAT_INTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 2154
            - containerPort: 4467
          volumeMounts:
            - name: validator-vol
              mountPath: /var/data
            - name: podinfo
              mountPath: /etc/podinfo

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

  volumeClaimTemplates:
    - metadata:
        name: validator-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: do-block-storage
