---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: validator
  serviceName: "validator"
  template:
    metadata:
      labels:
        name: validator
        dynamic-hostports: '2154' # Must be a string. Split multiple ports with '.'
    spec:
      containers:
        - name: validator
          image: quay.io/team-helium/validator:latest-val-amd64
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: "500Mi"
          command: [ "/bin/ash", "-c" ]
          args:
            - while [ -z $NAT_EXTERNAL_PORT ]; do
                port=$(cat /etc/podinfo/annotations | grep "k8s/2154" | grep -oE "\"[0-9]+\"" | grep -oE "[0-9]+" | xargs);

                if [ -n "$port" ]; then
                  export NAT_EXTERNAL_IP=$(wget -qO- ifconfig.me);
                  export NAT_EXTERNAL_PORT=$port;

                  echo "export NAT_EXTERNAL_IP=$NAT_EXTERNAL_IP" >> ~/.profile;
                  echo "export NAT_EXTERNAL_PORT=$NAT_EXTERNAL_PORT" >> ~/.profile;
                  break;
                fi;
                sleep 2;
              done;
              /opt/miner/bin/miner foreground;

          env:
            - name: NAT_INTERNAL_PORT
              value: "2154"
            - name: NAT_INTERNAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          ports:
            - containerPort: 2154
          volumeMounts:
            - name: validator-vol
              mountPath: /var/data
            - name: podinfo
              mountPath: /etc/podinfo
            - name: miner
              mountPath: /etc/miner

      volumes:
        - name: miner
          secret:
            secretName: swarm-keys
            defaultMode: 0400
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

  volumeClaimTemplates:
    - metadata:
        name: validator-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: do-block-storage
