---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helium-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helium-validator
  serviceName: "helium-validator"
  template:
    metadata:
      labels:
        name: helium-validator
    spec:
      containers:
        - name: monitor
          image: cpucpu/validator-monitor
          volumeMounts:
            - name: csi-pvc
              mountPath: "/var/data"
            - name: keys
              mountPath: "/etc/keys"

        - name: validator
          image: quay.io/team-helium/validator:latest-val-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 2154
          volumeMounts:
            - name: csi-pvc
              mountPath: "/var/data"
              
      volumes:
        - name: keys
          secret:
            secretName: swarm-keys
            defaultMode: 0400

  volumeClaimTemplates:
    - metadata:
        name: csi-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: do-block-storage