name: Validator Updater
on:
  schedule:
    - cron:  '*/15 * * * *'

  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update of all helium validators'
        default: '1'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Fetch .kube/config
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 helium-cluster
      
      - name: Update validator
        run: scripts/validator.sh update
          
