name: Scheduled Updater
on:
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update of all helium validators'
        default: '1'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
      
      - name: Setup kube config
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        
      - name: Output miner version
        run: kubectl exec -it helium-validator-0 -c validator -- /bin/sh -c "miner versions"